apiVersion: v1
kind: Pod
metadata:
  name: screenrecording
  labels:
    app: screenrecording
spec:
  containers:
  - image: robinhoodis/screenrecording:0.0.9
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: Always
    name: screenrecording
  restartPolicy: Always
